// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace winrt_mvvm
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Boolean TrySetMicaBackdrop();
        void OnActivated(IInspectable sender, Microsoft.UI.Xaml.WindowActivatedEventArgs  args);
        void OnClosed(IInspectable sender, Microsoft.UI.Xaml.WindowEventArgs args);
        void OnThemeChanged(Microsoft.UI.Xaml.FrameworkElement element, IInspectable sender);

    }
}
