import "ShellViewModel.idl";

namespace winrt_mvvm
{
    [default_interface]
    runtimeclass Shell : Microsoft.UI.Xaml.Controls.UserControl
    {
        Shell();
        ShellViewModel ViewModel;
        void OnAppWindowSizeChanged(IInspectable sender, Microsoft.UI.Xaml.WindowSizeChangedEventArgs args);
    }
}
