// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace winrt_mvvm
{
    [default_interface]
    runtimeclass TestPage : Microsoft.UI.Xaml.Controls.Page
    {
        TestPage();
        Int32 MyProperty;
    }
}
